server:
  port: 8086
  context-path: /
spring:
  thymeleaf:
      cash: false
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .jsp

#  profiles:
#    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    minIdle: 5
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    logSlowSql: true
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*/*Mapping.xml
  type-aliases-package: com.sun.demo.sys.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

lms:
  tempFilePath: d:/temp #临时下载文件路径